[package]
name = "binoxxo-webapp-seed"
version = "0.1.3"
authors = ["Martin Suesskraut <martin.suesskraut@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "Binoxxo as a webapp using wasm and seed"
repository = "https://github.com/msuesskraut/binoxxo-webapp-seed"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.3.2"
# note: wasm-bindgen 0.2.41 & 0.2.42 do not compile
wasm-bindgen = "^0.2.42"
web-sys = "^0.3.19"
binoxxo = { version = "^0.1.8", features = ["wasm-bindgen"] }
fluent-bundle = "^0.6.0"
elsa = "^1.0.2"
lazy_static = "^1.3.0"

# For serialization, eg sending requests to a server. Otherwise, not required.
serde = "^1.0.90"
serde_derive = "^1.0.90"
serde_json = "^1.0.39"

[dev-dependencies]
wasm-bindgen-test = "0.2"
