[package]
name = "binoxxo-webapp-seed"
version = "0.1.3"
authors = ["Martin Suesskraut <martin.suesskraut@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "Binoxxo as a webapp using wasm and seed"
repository = "https://github.com/msuesskraut/binoxxo-webapp-seed"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.3.1"
# note: wasm-bindgen 0.2.41 & 0.2.42 do not compile
wasm-bindgen = "=0.2.40"
web-sys = "=0.3.17"
binoxxo = { version = "^0.1.8", features = ["wasm-bindgen"] }
fluent = "0.6.0"

# For serialization, eg sending requests to a server. Otherwise, not required.
serde = "^1.0.90"
serde_derive = "^1.0.90"
serde_json = "^1.0.39"