[package]
name = "binoxxo-webapp-seed"
version = "0.3.0"
authors = ["Martin Suesskraut <martin.suesskraut@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "Binoxxo puzzle game as a webapp using wasm and seed"
repository = "https://github.com/msuesskraut/binoxxo-webapp-seed"
homepage = "https://msuesskraut.github.io/binoxxo/"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "0.3.7"
wasm-bindgen = "0.2.56"
web-sys = "0.3.33"
binoxxo = { version = "0.1.8", features = ["wasm-bindgen"] }
fluent-bundle = "0.9.1"
unic-langid = { version = "0.7.1", features = ["macros"] }
elsa = "1.3.2"
lazy_static = "1.4.0"

# For serialization, eg sending requests to a server. Otherwise, not required.
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"

[dev-dependencies]
wasm-bindgen-test = "0.3.6"
