[package]
name = "binoxxo-webapp-seed"
version = "0.1.1"
authors = ["Martin Suesskraut <martin.suesskraut@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "Binoxxo as a webapp using wasm and seed"
repository = "https://github.com/msuesskraut/binoxxo-webapp-seed"


[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.1.11"
wasm-bindgen = "^0.2.29"
web-sys = "^0.3.6"
binoxxo = { version = "^0.1.8", features = ["wasm-bindgen"] }

# For serialization, eg sending requests to a server. Otherwise, not required.
serde = "^1.0.80"
serde_derive = "^1.0.80"
serde_json = "1.0.33"