[package]
name = "binoxxo-webapp-seed"
version = "0.1.3"
authors = ["Martin Suesskraut <martin.suesskraut@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "Binoxxo puzzle game as a webapp using wasm and seed"
repository = "https://github.com/msuesskraut/binoxxo-webapp-seed"
homepage = "https://msuesskraut.github.io/binoxxo/"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "0.3.6"
wasm-bindgen = "0.2.47"
web-sys = "0.3.24"
binoxxo = { version = "0.1.8", features = ["wasm-bindgen"] }
fluent-bundle = "0.6.0"
elsa = "1.3.2"
lazy_static = "1.3.0"

# For serialization, eg sending requests to a server. Otherwise, not required.
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"

[dev-dependencies]
wasm-bindgen-test = "0.2"
